-- Flyway callback: runs on every migrate; top up all default attractions.
INSERT INTO attractions (id, name, description, country, image_url, created_by_user_id)
SELECT v.id, v.name, v.description, v.country, v.image_url, v.created_by_user_id
FROM (
    VALUES
        (1, 'Grand Canyon', 'Massive canyon carved by the Colorado River in Arizona', 'US', 'https://example.com/grand-canyon.jpg', 1),
        (2, 'Yosemite Valley', 'Glacial valley known for granite cliffs and waterfalls in California', 'US', 'https://example.com/yosemite-valley.jpg', 1),
        (3, 'Yellowstone Geysers', 'World-famous geothermal geysers and hot springs in Wyoming', 'US', 'https://example.com/yellowstone-geysers.jpg', 1),
        (4, 'Niagara Falls', 'Powerful waterfalls on the border of New York and Canada', 'US', 'https://example.com/niagara-falls.jpg', 1),
        (5, 'Great Smoky Mountains', 'Misty mountain range with rich biodiversity in Tennessee and North Carolina', 'US', 'https://example.com/great-smoky-mountains.jpg', 1),
        (6, 'Denali', 'North America''s tallest mountain located in Alaska', 'US', 'https://example.com/denali.jpg', 1),
        (7, 'Zion Canyon', 'Deep red canyon with towering sandstone cliffs in Utah', 'US', 'https://example.com/zion-canyon.jpg', 1),
        (8, 'Bryce Canyon Hoodoos', 'Unique rock spires known as hoodoos in southern Utah', 'US', 'https://example.com/bryce-canyon.jpg', 1),
        (9, 'Arches National Park', 'Desert landscape famous for natural sandstone arches in Utah', 'US', 'https://example.com/arches.jpg', 1),
        (10, 'Glacier National Park', 'Mountainous wilderness with glaciers and alpine lakes in Montana', 'US', 'https://example.com/glacier-national-park.jpg', 1),
        (11, 'Lake Tahoe', 'Clear alpine lake in the Sierra Nevada mountains', 'US', 'https://example.com/lake-tahoe.jpg', 1),
        (12, 'Mount Rainier', 'Snow-covered volcanic peak in Washington state', 'US', 'https://example.com/mount-rainier.jpg', 1),
        (13, 'Crater Lake', 'Deep blue lake formed in a collapsed volcano in Oregon', 'US', 'https://example.com/crater-lake.jpg', 1),
        (14, 'Death Valley Sand Dunes', 'Expansive desert dunes in the hottest place in North America', 'US', 'https://example.com/death-valley.jpg', 1),
        (15, 'Redwood National Park', 'Forest of the tallest trees on Earth in northern California', 'US', 'https://example.com/redwoods.jpg', 1),
        (16, 'Antelope Canyon', 'Narrow sandstone slot canyon known for light beams in Arizona', 'US', 'https://example.com/antelope-canyon.jpg', 1),
        (17, 'Monument Valley', 'Iconic desert valley with towering sandstone buttes', 'US', 'https://example.com/monument-valley.jpg', 1),
        (18, 'Everglades Wetlands', 'Subtropical wetlands ecosystem in southern Florida', 'US', 'https://example.com/everglades.jpg', 1),
        (19, 'Great Salt Lake', 'Large saltwater lake in northern Utah', 'US', 'https://example.com/great-salt-lake.jpg', 1),
        (20, 'Badlands National Park', 'Eroded buttes and dramatic rock formations in South Dakota', 'US', 'https://example.com/badlands.jpg', 1),
        (21, 'Joshua Tree Desert', 'Unique desert landscape with twisted Joshua trees in California', 'US', 'https://example.com/joshua-tree.jpg', 1),
        (22, 'Acadia Coastline', 'Rocky Atlantic coastline and forests in Maine', 'US', 'https://example.com/acadia.jpg', 1),
        (23, 'Havasu Falls', 'Turquoise waterfall oasis within the Grand Canyon region', 'US', 'https://example.com/havasu-falls.jpg', 1),
        (24, 'Devils Tower', 'Striking volcanic rock monolith rising from Wyoming plains', 'US', 'https://example.com/devils-tower.jpg', 1),
        (25, 'Lake Powell', 'Massive reservoir with dramatic canyon scenery in Utah and Arizona', 'US', 'https://example.com/lake-powell.jpg', 1),
        (26, 'Niagara Falls', 'Massive waterfalls located on the border of Ontario and New York', 'CA', 'https://example.com/niagara-falls-canada.jpg', 1),
        (27, 'Banff National Park', 'Mountain wilderness with turquoise lakes in Alberta', 'CA', 'https://example.com/banff.jpg', 1),
        (28, 'Lake Louise', 'Iconic glacial lake surrounded by the Canadian Rockies', 'CA', 'https://example.com/lake-louise.jpg', 1),
        (29, 'Moraine Lake', 'Brilliant blue alpine lake in the Valley of the Ten Peaks', 'CA', 'https://example.com/moraine-lake.jpg', 1),
        (30, 'Jasper National Park', 'Expansive wilderness park with glaciers and wildlife in Alberta', 'CA', 'https://example.com/jasper.jpg', 1),
        (31, 'Athabasca Glacier', 'Accessible glacier flowing from the Columbia Icefield', 'CA', 'https://example.com/athabasca-glacier.jpg', 1),
        (32, 'Yoho National Park', 'Rocky Mountain park known for waterfalls and fossil beds', 'CA', 'https://example.com/yoho.jpg', 1),
        (33, 'Emerald Lake', 'Vibrant green alpine lake in British Columbia', 'CA', 'https://example.com/emerald-lake.jpg', 1),
        (34, 'Bay of Fundy', 'Coastal bay known for the world''s highest tides', 'CA', 'https://example.com/bay-of-fundy.jpg', 1),
        (35, 'Hopewell Rocks', 'Flowerpot-shaped rock formations shaped by Fundy tides', 'CA', 'https://example.com/hopewell-rocks.jpg', 1),
        (36, 'Gros Morne National Park', 'Dramatic fjords and cliffs in Newfoundland', 'CA', 'https://example.com/gros-morne.jpg', 1),
        (37, 'Torngat Mountains', 'Remote Arctic mountains in northern Labrador', 'CA', 'https://example.com/torngat-mountains.jpg', 1),
        (38, 'Peggy''s Cove', 'Rocky Atlantic shoreline with dramatic granite formations', 'CA', 'https://example.com/peggys-cove.jpg', 1),
        (39, 'Algonquin Provincial Park', 'Vast forest park famous for lakes, moose, and canoeing', 'CA', 'https://example.com/algonquin.jpg', 1),
        (40, 'Nahanni National Park Reserve', 'Wild river canyon system in the Northwest Territories', 'CA', 'https://example.com/nahanni.jpg', 1),
        (41, 'Virginia Falls', 'Powerful waterfall twice the height of Niagara Falls', 'CA', 'https://example.com/virginia-falls.jpg', 1),
        (42, 'Lake Superior Shoreline', 'Dramatic cliffs and beaches along the largest Great Lake', 'CA', 'https://example.com/lake-superior.jpg', 1),
        (43, 'Spirit Island', 'Small picturesque island in Maligne Lake', 'CA', 'https://example.com/spirit-island.jpg', 1),
        (44, 'Churchill Polar Bear Coast', 'Arctic tundra known for polar bear migrations', 'CA', 'https://example.com/churchill.jpg', 1),
        (45, 'Cape Breton Highlands', 'Rugged coastal cliffs and forests in Nova Scotia', 'CA', 'https://example.com/cape-breton.jpg', 1),
        (46, 'Icefields Parkway', 'Scenic mountain corridor through glaciers and peaks', 'CA', 'https://example.com/icefields-parkway.jpg', 1),
        (47, 'Great Bear Rainforest', 'Vast coastal rainforest in British Columbia', 'CA', 'https://example.com/great-bear-rainforest.jpg', 1),
        (48, 'Dinosaur Provincial Park', 'Badlands landscape rich with dinosaur fossils', 'CA', 'https://example.com/dinosaur-park.jpg', 1),
        (49, 'Waterton Lakes National Park', 'Mountain lakes and prairies meeting in southern Alberta', 'CA', 'https://example.com/waterton-lakes.jpg', 1),
        (50, 'Haida Gwaii Islands', 'Remote Pacific archipelago with wild coastline and forests', 'CA', 'https://example.com/haida-gwaii.jpg', 1),
        (51, 'Copper Canyon', 'Massive canyon system in Chihuahua larger and deeper than the Grand Canyon', 'MX', 'https://example.com/copper-canyon.jpg', 1),
        (52, 'Sumidero Canyon', 'Towering canyon cliffs rising above the Grijalva River in Chiapas', 'MX', 'https://example.com/sumidero-canyon.jpg', 1),
        (53, 'Hierve el Agua', 'Petrified mineral waterfalls and natural pools in Oaxaca', 'MX', 'https://example.com/hierve-el-agua.jpg', 1),
        (54, 'Cenote Ik Kil', 'Deep natural limestone sinkhole filled with clear water in Yucatan', 'MX', 'https://example.com/cenote-ik-kil.jpg', 1),
        (55, 'Sian Ka''an Biosphere Reserve', 'Protected tropical wetlands and coral reef ecosystem in Quintana Roo', 'MX', 'https://example.com/sian-kaan.jpg', 1),
        (56, 'Monarch Butterfly Biosphere Reserve', 'Mountain forests where millions of monarch butterflies migrate each winter', 'MX', 'https://example.com/monarch-butterflies.jpg', 1),
        (57, 'Grutas de Tolantongo', 'Thermal spring pools and caves set into a canyon in Hidalgo', 'MX', 'https://example.com/tolantongo.jpg', 1),
        (58, 'Nevado de Toluca', 'Extinct volcano with crater lakes in central Mexico', 'MX', 'https://example.com/nevado-de-toluca.jpg', 1),
        (59, 'Pico de Orizaba', 'Mexico''s tallest mountain and a snow-capped stratovolcano', 'MX', 'https://example.com/pico-de-orizaba.jpg', 1),
        (60, 'Paricutin Volcano', 'Young volcano that dramatically emerged from a cornfield in 1943', 'MX', 'https://example.com/paricutin.jpg', 1),
        (61, 'Lagunas de Montebello', 'Cluster of colorful mountain lakes near the Guatemala border', 'MX', 'https://example.com/montebello-lakes.jpg', 1),
        (62, 'Cascada de Tamul', 'One of Mexico''s tallest waterfalls located in San Luis Potosi', 'MX', 'https://example.com/tamul-waterfall.jpg', 1),
        (63, 'Huasteca Potosina', 'Region of turquoise rivers, waterfalls, and jungle landscapes', 'MX', 'https://example.com/huasteca-potosina.jpg', 1),
        (64, 'Islas Marietas', 'Pacific islands known for wildlife and the hidden beach', 'MX', 'https://example.com/marietas-islands.jpg', 1),
        (65, 'Balandra Beach', 'Protected bay with turquoise water and white sand in Baja California Sur', 'MX', 'https://example.com/balandra-beach.jpg', 1),
        (66, 'Cabo Pulmo Reef', 'Thriving coral reef ecosystem in the Sea of Cortez', 'MX', 'https://example.com/cabo-pulmo.jpg', 1),
        (67, 'Valle de los Cirios', 'Desert landscape filled with towering cactus and rare plants', 'MX', 'https://example.com/valle-de-los-cirios.jpg', 1),
        (68, 'Basaseachic Falls', 'One of the tallest waterfalls in Mexico located in Chihuahua', 'MX', 'https://example.com/basaseachic-falls.jpg', 1),
        (69, 'Cenote Dos Ojos', 'Famous underwater cave system for diving in the Riviera Maya', 'MX', 'https://example.com/cenote-dos-ojos.jpg', 1),
        (70, 'Sierra Gorda Biosphere Reserve', 'Mountain ecosystem with forests, rivers, and wildlife in Queretaro', 'MX', 'https://example.com/sierra-gorda.jpg', 1),
        (71, 'Laguna Bacalar', 'Clear freshwater lagoon known as the Lake of Seven Colors', 'MX', 'https://example.com/bacalar.jpg', 1),
        (72, 'Isla Espiritu Santo', 'Wild island sanctuary with sea lions and pristine beaches', 'MX', 'https://example.com/espiritu-santo.jpg', 1),
        (73, 'Popocatepetl Volcano', 'Active volcano towering near Mexico City', 'MX', 'https://example.com/popocatepetl.jpg', 1),
        (74, 'Iztaccihuatl Volcano', 'Snow-capped dormant volcano known as the Sleeping Woman', 'MX', 'https://example.com/iztaccihuatl.jpg', 1),
        (75, 'Celestun Biosphere Reserve', 'Coastal wetlands famous for large flamingo populations', 'MX', 'https://example.com/celestun.jpg', 1)
) AS v(id, name, description, country, image_url, created_by_user_id)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('attractions', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM attractions),
    true
);

